<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Calculator_iPhone XR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>46677dc6-e24d-4b7a-93aa-6514a0c798b9</testSuiteGuid>
   <testCaseLink>
      <guid>c5ad2166-ee22-4132-8fc2-b12e2d0c4d7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android And iOS/DOFF-11217_Register Or Calculator</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3a8a1d37-97be-438d-9a89-ee5d4a4f1acd</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>13</value>
         </iterationEntity>
         <testDataId>Data Files/Device Farm</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3a8a1d37-97be-438d-9a89-ee5d4a4f1acd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DeviceName</value>
         <variableId>9fb33da1-8c11-415f-93a7-6fd60d7af839</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3a8a1d37-97be-438d-9a89-ee5d4a4f1acd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UdId</value>
         <variableId>13bd77ca-65d8-462b-acc0-ff53b47baf71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3a8a1d37-97be-438d-9a89-ee5d4a4f1acd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformVersion</value>
         <variableId>ed39d827-a5bd-4ddf-9282-644e8a4c41b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3a8a1d37-97be-438d-9a89-ee5d4a4f1acd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformName</value>
         <variableId>0e9d02b8-6aa1-4007-b32d-d6178f7b9a6c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
