<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Calculator_iPhone 6s</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>7b8a9d5e-1fca-46f4-a1c2-32771fab61a9</testSuiteGuid>
   <testCaseLink>
      <guid>8ef76311-da3b-4791-9dbf-0bfd96a90cf7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android And iOS/DOFF-11217_Register Or Calculator</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b065cfd7-8681-40a6-a69d-fb1a6d0cdbab</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>15</value>
         </iterationEntity>
         <testDataId>Data Files/Device Farm</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b065cfd7-8681-40a6-a69d-fb1a6d0cdbab</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DeviceName</value>
         <variableId>9fb33da1-8c11-415f-93a7-6fd60d7af839</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b065cfd7-8681-40a6-a69d-fb1a6d0cdbab</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UdId</value>
         <variableId>13bd77ca-65d8-462b-acc0-ff53b47baf71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b065cfd7-8681-40a6-a69d-fb1a6d0cdbab</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformVersion</value>
         <variableId>ed39d827-a5bd-4ddf-9282-644e8a4c41b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b065cfd7-8681-40a6-a69d-fb1a6d0cdbab</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformName</value>
         <variableId>0e9d02b8-6aa1-4007-b32d-d6178f7b9a6c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
