<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Register - Xiaomi Mi MIX 2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>10025eed-ede8-40a5-8c3b-71a4c06fed17</testSuiteGuid>
   <testCaseLink>
      <guid>9181b3f0-ee7d-4ca4-a65e-d3c0d4c8c12e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android And iOS/Register Or Calculator</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f9a5863c-64b2-4f2f-94f5-81bd660695ae</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>6</value>
         </iterationEntity>
         <testDataId>Data Files/Device Farm</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f9a5863c-64b2-4f2f-94f5-81bd660695ae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DeviceName</value>
         <variableId>cbdc8434-c7ea-476a-aa10-9eceb97f1e55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f9a5863c-64b2-4f2f-94f5-81bd660695ae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UdId</value>
         <variableId>e9ad741b-3e9a-4f16-b1ea-135301bc2d74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f9a5863c-64b2-4f2f-94f5-81bd660695ae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformVersion</value>
         <variableId>7061dc43-7e42-42bb-9486-4f567eb9b6fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f9a5863c-64b2-4f2f-94f5-81bd660695ae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformName</value>
         <variableId>3a55db9b-bdfb-4d39-9764-50cf67306b61</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
