<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Register - Samsung SM-S918B</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8b08da90-9774-4453-9f7d-1aa26103c860</testSuiteGuid>
   <testCaseLink>
      <guid>5af6d87a-d9ae-4886-92f5-748188ca0925</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android And iOS/DOFF-11217_Register Or Calculator</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f544aec3-176a-4af6-b1dc-3fc68430caad</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>11</value>
         </iterationEntity>
         <testDataId>Data Files/Device Farm</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f544aec3-176a-4af6-b1dc-3fc68430caad</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DeviceName</value>
         <variableId>9fb33da1-8c11-415f-93a7-6fd60d7af839</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f544aec3-176a-4af6-b1dc-3fc68430caad</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UdId</value>
         <variableId>13bd77ca-65d8-462b-acc0-ff53b47baf71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f544aec3-176a-4af6-b1dc-3fc68430caad</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformVersion</value>
         <variableId>ed39d827-a5bd-4ddf-9282-644e8a4c41b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f544aec3-176a-4af6-b1dc-3fc68430caad</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformName</value>
         <variableId>0e9d02b8-6aa1-4007-b32d-d6178f7b9a6c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
