<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Register - Samsung SM-A520F</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>10ca16b6-43ad-4651-a5ed-b942cf5b6f03</testSuiteGuid>
   <testCaseLink>
      <guid>90866331-8d50-479c-bad1-d3e4435784bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android And iOS/DOFF-16321_Register Or Calculator</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>40c69f7a-75ac-4cfc-8fc6-bf9a8fb8a804</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/Device Farm</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>40c69f7a-75ac-4cfc-8fc6-bf9a8fb8a804</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DeviceName</value>
         <variableId>cbdc8434-c7ea-476a-aa10-9eceb97f1e55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>40c69f7a-75ac-4cfc-8fc6-bf9a8fb8a804</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UdId</value>
         <variableId>e9ad741b-3e9a-4f16-b1ea-135301bc2d74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>40c69f7a-75ac-4cfc-8fc6-bf9a8fb8a804</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformVersion</value>
         <variableId>7061dc43-7e42-42bb-9486-4f567eb9b6fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>40c69f7a-75ac-4cfc-8fc6-bf9a8fb8a804</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformName</value>
         <variableId>3a55db9b-bdfb-4d39-9764-50cf67306b61</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
