<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Register - Samsung SM-A520F</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>10ca16b6-43ad-4651-a5ed-b942cf5b6f03</testSuiteGuid>
   <testCaseLink>
      <guid>90866331-8d50-479c-bad1-d3e4435784bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/DOFF-11217_Register Success</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>40c69f7a-75ac-4cfc-8fc6-bf9a8fb8a804</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/Device Farm</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>40c69f7a-75ac-4cfc-8fc6-bf9a8fb8a804</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DeviceName</value>
         <variableId>9fb33da1-8c11-415f-93a7-6fd60d7af839</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>40c69f7a-75ac-4cfc-8fc6-bf9a8fb8a804</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UdId</value>
         <variableId>13bd77ca-65d8-462b-acc0-ff53b47baf71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>40c69f7a-75ac-4cfc-8fc6-bf9a8fb8a804</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformVersion</value>
         <variableId>ed39d827-a5bd-4ddf-9282-644e8a4c41b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>40c69f7a-75ac-4cfc-8fc6-bf9a8fb8a804</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformName</value>
         <variableId>0e9d02b8-6aa1-4007-b32d-d6178f7b9a6c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
