<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Calculator_iPhone 6s</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>7b8a9d5e-1fca-46f4-a1c2-32771fab61a9</testSuiteGuid>
   <testCaseLink>
      <guid>8ef76311-da3b-4791-9dbf-0bfd96a90cf7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android And iOS/Register Or Calculator</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b065cfd7-8681-40a6-a69d-fb1a6d0cdbab</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>15</value>
         </iterationEntity>
         <testDataId>Data Files/Device Farm</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b065cfd7-8681-40a6-a69d-fb1a6d0cdbab</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DeviceName</value>
         <variableId>cbdc8434-c7ea-476a-aa10-9eceb97f1e55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b065cfd7-8681-40a6-a69d-fb1a6d0cdbab</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UdId</value>
         <variableId>e9ad741b-3e9a-4f16-b1ea-135301bc2d74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b065cfd7-8681-40a6-a69d-fb1a6d0cdbab</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformVersion</value>
         <variableId>7061dc43-7e42-42bb-9486-4f567eb9b6fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b065cfd7-8681-40a6-a69d-fb1a6d0cdbab</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformName</value>
         <variableId>3a55db9b-bdfb-4d39-9764-50cf67306b61</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
