<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Calculator_iPhone 5s</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c7480ff3-172e-43f9-ba18-1d972d8917d8</testSuiteGuid>
   <testCaseLink>
      <guid>a3d5125b-b334-4b4f-ac23-173cb52ccabe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android And iOS/Register Or Calculator</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>39bf6bed-01c8-4598-9cb6-fa024a2783f1</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>16</value>
         </iterationEntity>
         <testDataId>Data Files/Device Farm</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>39bf6bed-01c8-4598-9cb6-fa024a2783f1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DeviceName</value>
         <variableId>cbdc8434-c7ea-476a-aa10-9eceb97f1e55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>39bf6bed-01c8-4598-9cb6-fa024a2783f1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UdId</value>
         <variableId>e9ad741b-3e9a-4f16-b1ea-135301bc2d74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>39bf6bed-01c8-4598-9cb6-fa024a2783f1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformVersion</value>
         <variableId>7061dc43-7e42-42bb-9486-4f567eb9b6fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>39bf6bed-01c8-4598-9cb6-fa024a2783f1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformName</value>
         <variableId>3a55db9b-bdfb-4d39-9764-50cf67306b61</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
