<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Casper_Duplicate</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4cbc1b13-0f5b-4a70-ad39-fc06f7fbec8f</testSuiteGuid>
   <testCaseLink>
      <guid>11beac50-2a3c-4ee4-86a1-3b6e23afc65b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android And iOS/Register Or Calculator</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f6702174-0716-4a2c-afba-ad58de811967</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>7</value>
         </iterationEntity>
         <testDataId>Data Files/Device Farm</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f6702174-0716-4a2c-afba-ad58de811967</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DeviceName</value>
         <variableId>cbdc8434-c7ea-476a-aa10-9eceb97f1e55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f6702174-0716-4a2c-afba-ad58de811967</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UdId</value>
         <variableId>e9ad741b-3e9a-4f16-b1ea-135301bc2d74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f6702174-0716-4a2c-afba-ad58de811967</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformVersion</value>
         <variableId>7061dc43-7e42-42bb-9486-4f567eb9b6fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f6702174-0716-4a2c-afba-ad58de811967</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PlatformName</value>
         <variableId>3a55db9b-bdfb-4d39-9764-50cf67306b61</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
