<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>Angka 2</name>
   <tag></tag>
   <elementGuidId>ebb12de4-7917-4f09-a9c9-05f97c15868e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ee1208c2-95f1-48e6-836a-c61e5478090f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>39415c50-def8-4537-973d-601997ad0c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeButton[@name=&quot;2&quot;]</value>
      <webElementGuid>a71fc136-d795-4675-9ae8-6a8e226d503b</webElementGuid>
   </webElementProperties>
   <locator>//XCUIElementTypeButton[@name=&quot;2&quot;]</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
