<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>Angka 8</name>
   <tag></tag>
   <elementGuidId>fb40c16d-8f5b-4091-a03d-c0d124d7b63f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>e4f81fc3-b126-4c00-ac7d-b1f4e90bfa2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>4f058da6-66e7-47c1-8df7-f734cde59138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeButton[@name=&quot;8&quot;]</value>
      <webElementGuid>ddbbca9b-7b39-44aa-a9ac-a38246ffb55c</webElementGuid>
   </webElementProperties>
   <locator>//XCUIElementTypeButton[@name=&quot;8&quot;]</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
